// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs75CzicLBMrgza5ijPyf6to8ob_mStAk',
    appId: '1:888250422938:android:42ddb90ee8d946f2737123',
    messagingSenderId: '888250422938',
    projectId: 'chat-app-b80f9',
    storageBucket: 'chat-app-b80f9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEerJOhKWLCHwyCLRXqZILSnHPn_R1-0A',
    appId: '1:888250422938:web:ed50eb26fe94c8aa737123',
    messagingSenderId: '888250422938',
    projectId: 'chat-app-b80f9',
    authDomain: 'chat-app-b80f9.firebaseapp.com',
    storageBucket: 'chat-app-b80f9.firebasestorage.app',
    measurementId: 'G-7QFGDR5JWX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS1KoeeAnLigos3umIuu_P9DC6x5dzOlg',
    appId: '1:888250422938:ios:822d75090947d600737123',
    messagingSenderId: '888250422938',
    projectId: 'chat-app-b80f9',
    storageBucket: 'chat-app-b80f9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS1KoeeAnLigos3umIuu_P9DC6x5dzOlg',
    appId: '1:888250422938:ios:822d75090947d600737123',
    messagingSenderId: '888250422938',
    projectId: 'chat-app-b80f9',
    storageBucket: 'chat-app-b80f9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEerJOhKWLCHwyCLRXqZILSnHPn_R1-0A',
    appId: '1:888250422938:web:981e6af4a9b039cf737123',
    messagingSenderId: '888250422938',
    projectId: 'chat-app-b80f9',
    authDomain: 'chat-app-b80f9.firebaseapp.com',
    storageBucket: 'chat-app-b80f9.firebasestorage.app',
    measurementId: 'G-ZNRMMX2407',
  );

}